### ISSUE TITLE
🚀 Feature: specify node version (via `.nvmrc` or otherwise)

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/teach-la-ts-react-starter#115]
We should somehow specify the node version for projects *in the project itself*. This helps with CI reproducibility, documentation, etc.

### Use Case

1. Standardizing node versions across developers is quite useful and reduces bugs
2. Fixes CD builds failing since Netlify infers a wrong version of node (see #111, #108)
3. Builds good practice in terms of keeping track of Node LTS release schedule

### Proposed Solution

* consider adding an `.nvmrc` (see: [nvm](https://github.com/nvm-sh/nvm))
* consider adding something to the `engines` field of `package.json` (see: [npm docs for the field](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines))
* consider enforcing `engine-strict=true` in `.npmrc` (see: [SO post](https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json))
* update CI/CD to use this properly 
    * note that right now, there's an action to build on node 14, but the LTS Is node 16; we should be using that (and maybe, latest?)
* add relevant documentation (probably to README)

- [x] :wave: I may be able to implement this feature request (but it may be a good ticket for someone else to take)

---

This is a :rocket: Feature Request

**Comment by reginawang3495** [comment]
For this update: https://github.com/uclaacm/teach-la-ts-react-starter/pull/116

```
requires Node.js version ^12.20.0 || ^14.13.1 || >=16.0.0.
```

If we could adhere to that and merge in that PR!
